name: Build VoidLink IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: Integration
          submodules: recursive

      - name: Compile and Build Unsigned IPA
        run: |
          xcodebuild clean build -project Moonlight.xcodeproj -scheme "Moonlight" -configuration Release -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -derivedDataPath Build_out
          mkdir Payload
          cp -R Build_out/Build/Products/Release-iphoneos/Moonlight.app Payload/
          zip -r VoidLink.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoidLink-IPA
          path: VoidLink.ipa
